version: '3.7'

services:
  db:
    container_name: database_backup
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"